version: '3.8'

services:
  web:
    build: .
    environment:
      - LDAP_HOST=${LDAP_HOST}
      - LDAP_BIND_DN=${LDAP_BIND_DN}
      - LDAP_BIND_PASSWORD=${LDAP_BIND_PASSWORD}
      - LDAP_SEARCH_BASE=${LDAP_SEARCH_BASE}
      - LDAP_CERT_PATH=${LDAP_CERT_PATH}
      - LDAP_KEY_PATH=${LDAP_KEY_PATH}
      - LDAP_REJECT_UNAUTHORIZED=${LDAP_REJECT_UNAUTHORIZED}
      - SECRET_KEY=${SECRET_KEY}
      - PORT=${PORT:-3000}
      - NODE_ENV=${NODE_ENV:-production}
      - MONGODB_ROOT_USER=${MONGODB_ROOT_USER:-root}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_HOST=${MONGODB_HOST:-database}

  database:
    image: bitnami/mongodb:6.0.3
    volumes:
     - data:/bitname/mongodb
    environment:
     - MONGODB_ROOT_USER=${MONGODB_ROOT_USER:-root}
     - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
     - MONGODB_EXTRA_FLAGS=${MONGODB_EXTRA_FLAGS:---wiredTigerCacheSizeGB=2}

volumes:
  data:
