version: '3.8'
services:
  web:
    build:
      context: .devcontainer
    environment:
      - NODE_ENV:development

    volumes:
      - .:/workspaces/micuenta:cached

  database:
    ports:
      - 27017:27017
